# Generated by Django 2.1.1 on 2018-10-11 12:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('credit_score', models.PositiveIntegerField(db_index=True, verbose_name='Скоринговый балл')),
                ('offer_matching_mode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Авто')], max_length=10), db_index=True, default=['manual', 'auto'], size=2, verbose_name='Режим создания заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Анкета клиента',
                'verbose_name_plural': 'Анкеты клиентов',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.Partner', verbose_name='Партнёр'),
        ),
    ]
