# Generated by Django 2.1.1 on 2018-10-11 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кредитной организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кредитная организация',
                'verbose_name_plural': 'Кредитные организации',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предложения')),
                ('offer_type', models.PositiveIntegerField(choices=[(1, 'Потребительский'), (2, 'Ипотека'), (3, 'Автокредит')], verbose_name='Тип предложения')),
                ('rotating_start', models.DateTimeField(db_index=True, verbose_name='Начало ротации')),
                ('rotating_end', models.DateTimeField(db_index=True, verbose_name='Конец ротации')),
                ('min_credit_score', models.PositiveIntegerField(db_index=True, verbose_name='Минимальный скоринговый балл')),
                ('max_credit_score', models.PositiveIntegerField(db_index=True, verbose_name='Максимальный скоринговый балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lenders.Lender', verbose_name='Кредитная организация')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
